export const ActionTypes = {
  LOCATION: {
    FETCH: {
      SUCCESS: 'LOCATION_FETCH_SUCCESS',
      FAILURE: 'LOCATION_FETCH_FAILURE',
    },
    WATCH: {
      START: 'LOCATION_WATCH_START',
      STOP: 'LOCATION_WATCH_STOP',
    },
  },
  ROUTE: {
    FETCH_ALL: {
      SUCCESS: 'ROUTE_FETCH_ALL_SUCCESS',
    },
    SELECT: 'ROUTE_SELECT',
    DIRECTION: {
      SELECT: 'ROUTE_DIRECTION_SELECT',
    },
  },
  STOP: {
    FETCH_ALL: {
      SUCCESS: 'STOP_FETCH_ALL_SUCCESS',
    },
    SELECT: {
      INITIAL: 'STOP_SELECT_INITIAL',
      FINAL: 'STOP_SELECT_FINAL',
    },
  },
  TRIP: {
    FETCH: {
      SUCCESS: 'TRIP_FETCH_SUCCESS',
      FAILURE: 'TRIP_FETCH_FAILURE',
    },
    WATCH: {
      START: 'TRIP_WATCH_START',
      STOP: 'TRIP_WATCH_STOP',
    },
  },
  BUZZ: {
    FETCH_SAVED_PATTERNS: {
      SUCCESS: 'BUZZ_FETCH_SAVED_PATTERNS_SUCCESS',
    },
  },
};
